### ISSUE TITLE
get_schema_names inconsistency

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool-avro#10]
Have problem with nested records:
Output
```yaml
---
- a.b
- a.c
- d
- e
- f
- j
...
```
path `a` is alse valid =(

**Comment by mejedi** [comment]
That's by design.

`get_schema_names()`/`get_schema_types()` both return an array of N items where N is the size of a tuple produced by flattening. Each item in names/types array corresponds to the tuple element providing names/types map.

It was designed to make it possible to bypass Avro and update tuples directly. 

Ex: `++` attribute `a.c`.
   * Step 1: find `a.c` index in tuple (2).
   * Step 2: check that `a.c` is an int.
   * Step 3: execute update.

To make it possible to validate names fast one is going to build a dictionary from `get_schema_names()` results, anyway. One can generate all valid prefixes for names with dots when building a dictionary.
